# Generated by Django 2.2.16 on 2020-10-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='domain',
        ),
    ]
