# Generated by Django 2.2.16 on 2020-10-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sso', '0002_remove_assignment_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='copy',
        ),
    ]
