# Generated by Django 2.2.16 on 2021-10-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sso', '0003_remove_assignment_copy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='username_mode',
            new_name='match_mode',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='match_mode',
            field=models.IntegerField(choices=[(0, 'any'), (1, 'username matches'), (3, 'has group'), (4, 'is staff'), (5, 'is superuser')]),
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='username',
            new_name='match',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='match',
            field=models.CharField(blank=True, max_length=255, verbose_name='Match Pattern'),
        ),
    ]
