# Generated by Django 2.2.4 on 2019-09-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('sink', models.CharField(max_length=50)),
                ('permanent', models.BooleanField(default=False)),
            ],
        ),
    ]
