# Generated by Django 2.2.4 on 2019-09-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='sink',
            field=models.CharField(max_length=250),
        ),
    ]
