# Generated by Django 2.2.16 on 2020-10-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0003_auto_20201006_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='usages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='sink',
            field=models.URLField(max_length=250),
        ),
    ]
