# Generated by Django 2.2.16 on 2020-10-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0004_auto_20201006_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='usages',
            field=models.PositiveIntegerField(default=0, help_text='The number of times that link has been used'),
        ),
    ]
