# Generated by Django 2.2.16 on 2020-10-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0005_auto_20201006_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='sink',
            field=models.URLField(max_length=1024),
        ),
    ]
